version: "3.7"

services:

  dp-apache:
    build: 
      context: ./conf/apache
    image: dp-apache2.4-ssl:1.0
    container_name: dp-apache
    environment:
      - SERVER_NAME=${SSL_DOMAIN}
    ports:
      - "${UNSECURE_HOST_PORT}:80"
      - "${SECURE_HOST_PORT}:443"
    depends_on:
      - dp-php
    links:
      - dp-php
    volumes: 
      - "${APP_DIR}:/usr/local/apache2/htdocs:ro"

  dp-php:
    build:
      context: ./conf/php
    image: dp-php7.4-fpm:1.0
    container_name: dp-php
    ports:
      - "${XDEBUG_HOST_PORT}:9001"
    volumes:
      - "${APP_DIR}:/var/www/html:rw"
